
/** Actions related to the Sidebar Menu */
export const IS_OBJECT_LIST_SHOWN = 'IS_OBJECT_LIST_SHOWN';

export const SELECT_OBJECT_LIST = 'SELECT_OBJECT_LIST';

/** Actions related to Retreiving Data */
export const RETRIEVE_TRACKING_DATA = 'RETRIEVE_TRACKING_DATA';

export const SHOULD_UPDATE_TRACKING_DATA = 'SHOULD_UPDATE_TRACKING_DATA';

export const CHANGE_LOCATION_ACCURACY = 'CHANGE_LOCATION_ACCURACY'

export const RETRIEVE_OBJECT_TABLE = 'RETRIEVE_OBJECT_TABLE'